# Define the Docker image to use for the pipeline
image: mcr.microsoft.com/playwright:v1.54.1-jammy

# Define the stages of your pipeline
stages:
  - test

# Cache Python and Node.js dependencies
cache:
  paths:
    - .venv/
    - __pycache__/
    - "*.pyc"
    - node_modules/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_DEFAULT_TIMEOUT: 60
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

# Install dependencies
before_script:
  - apt-get update && apt-get install -y python3 python3-pip python3-venv
  - python3 --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - npm install -g npm@latest
  - npm install -g @playwright/test@1.54.1

# Test stage
playwright_tests:
  stage: test
  script:
    - echo "Running tests..."
    - npx playwright install
    - npx playwright install-deps
    - npx playwright test --reporter=html
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 1 week
