image: mcr.microsoft.com/playwright:v1.45.1  # Uses Node & browsers pre-installed

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_DEFAULT_TIMEOUT: "60"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

cache:
  paths:
    - .venv/
    - __pycache__/
    - "*.pyc"

playwright_tests:
  stage: test
  script:
    - echo "Running tests..."
    - npx playwright install
    - npx playwright install-deps
    - npx playwright test --reporter=html
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 1 week
