version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-focal
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright browsers
          command: npx playwright install
      - run:
          name: Run Playwright PlanetSportBet test only
          command: npx playwright test tests/planetsportbet-inplay-animation.spec.ts --reporter=dot
workflows:
  test:
    jobs:
      - test
