#!/bin/bash
# Disable strict error mode - continue even if tests fail
set +e

ROOT="/Users/davidjarrett/Documents/sport-test-automator-main-1"
cd "$ROOT"

# SMTP config (allow override via env or .env)
if [ -f .env ]; then
  # shellcheck disable=SC2046
  export $(grep -E '^(SMTP_USER|SMTP_PASSWORD|RECIPIENTS)=' .env | xargs)
fi
export SMTP_USER="${SMTP_USER:-davidjarrett001@gmail.com}"
export SMTP_PASSWORD="${SMTP_PASSWORD:-xbzndaxkfnpoxnuo}"
export RECIPIENTS="${RECIPIENTS:-davidjarrett001@gmail.com}"

echo "🚀 Starting all 11 tests at $(TZ='Europe/London' date '+%Y-%m-%d %H:%M:%S UK Time')"

# Helper to send simple email
send_email() {
  local subject="$1"
  local body="$2"
  # Fallback: if body is empty, inject a minimal diagnostic body
  if [ -z "$(echo "$body" | tr -d '\r\n\t ' )" ]; then
    body="<div style=\"font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif\"><h3>Empty report fallback</h3><p>No details were generated by the runner. Check parsing of output and grep/awk patterns.</p></div>"
  fi
  # Explicitly pass environment variables to Python
  SMTP_USER="$SMTP_USER" SMTP_PASSWORD="$SMTP_PASSWORD" RECIPIENTS="$RECIPIENTS" python3 scripts/send_email.py --html "$subject" "$body"
  echo "Email notification sent successfully: $subject"
}

# Helper to parse PASS/FAIL from test output
parse_results() {
  local out_file="$1"
  # Try PSG/StarSports style output first
  local pass=$(grep -E "^✅ Events with Animations \(PASS\):|^✅ Total Passed:" "$out_file" 2>/dev/null | awk -F': ' '{print $2}' | awk '{s+=$1} END{print s+0}')
  local fail=$(grep -E "^❌ Events without Animations \(FAIL\):|^❌ Total Failed:" "$out_file" 2>/dev/null | awk -F': ' '{print $2}' | awk '{s+=$1} END{print s+0}')
  
  # If not found, try counting PASSED/FAILED EVENTS entries
  if [ "${pass:-0}" -eq 0 ]; then
    pass=$(grep -c "^✅ PASS:" "$out_file" 2>/dev/null || echo "0")
  fi
  if [ "${fail:-0}" -eq 0 ]; then
    fail=$(grep -c "^❌ FAIL:" "$out_file" 2>/dev/null || echo "0")
  fi
  
  echo "${pass},${fail}"
}

# Helper to extract detailed event lists from test output (matches run_requested_email.sh)
extract_event_details() {
  local out_file="$1"
  local passed_list failed_list combined_list
  
  # Extract passed events - ALL sections, not just first
  passed_list=$(awk '/^✅ PASSED EVENTS \([0-9]+\):/{flag=1;next} flag && /^[0-9]+\./{line=$0; sub(/^[0-9]+\.\s*/,"",line); print line; next} flag && /^❌ FAILED EVENTS|^🔍 Looking for/{flag=0}' "$out_file" | sed 's/^/✅ /')
  
  # Extract failed events - ALL sections, not just first  
  failed_list=$(awk '/^❌ FAILED EVENTS \([0-9]+\):/{flag=1;next} flag && /^[0-9]+\./{line=$0; sub(/^[0-9]+\.\s*/,"",line); print line; next} flag && /^✅ PASSED EVENTS|^🔍 Looking for|^🏁/{flag=0}' "$out_file" | sed 's/^/❌ /')
  
  # Fallback: try line-by-line PASS/FAIL format (StarSports style)
  if [ -z "$passed_list" ]; then
    passed_list=$(awk '/^✅ PASS: /{sub(/^✅ PASS: /,"✅ "); print}' "$out_file")
  fi
  if [ -z "$failed_list" ]; then
    failed_list=$(awk '/^❌ FAIL: /{sub(/^❌ FAIL: /,"❌ "); print}' "$out_file")
  fi
  
  # Combine and number the list
  combined_list=$( ( printf "%s\n" "$passed_list"; printf "%s\n" "$failed_list" ) | sed '/^$/d' | nl -w1 -s'.  ' )
  
  echo "$combined_list"
}

# Build detailed email body with event lists (matches run_requested_email.sh format)
build_detailed_email() {
  local icon="$1"
  local title="$2"
  local pass="$3"
  local fail="$4"
  local out_file="$5"
  
  local total=$((pass + fail))
  local success_rate=0
  if [ "$total" -gt 0 ]; then
    success_rate=$(( (pass * 100) / total ))
  fi
  
  local uk_time combined_list
  uk_time=$(TZ='Europe/London' date '+%d %B %Y %H:%M:%S UK Time')
  combined_list=$(extract_event_details "$out_file")
  
  local body="<div style=\"font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif\">"
  body+="<h2>${title} – Automated Results</h2>"
  body+="<p><strong>Run Time:</strong> ${uk_time}</p>"
  body+="<p><strong>Total:</strong> ${total} | <strong>Pass:</strong> ${pass} | <strong>Fail:</strong> ${fail} | <strong>Success:</strong> ${success_rate}%</p>"
  
  if [ -n "$combined_list" ]; then
    body+="<h3>Event Results</h3>"
    body+="<pre style=\"white-space:pre-wrap;font-family:monospace\">${combined_list}</pre>"
  else
    body+="<p><em>No detailed event information available in test output.</em></p>"
  fi
  
  body+="</div>"
  
  echo "$body"
}

# 1. PSG Football
echo ""
echo "========================================"
echo "1/11: PSG Football"
echo "========================================"
OUT="/tmp/psg_football.out"
npx playwright test tests/specs/planetsports/PSG.Football.Animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "⚽" "PSG Football – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "⚽ PSG Football – Test Results" "$BODY"

# 2. PSG Cricket
echo ""
echo "========================================"
echo "2/11: PSG Cricket"
echo "========================================"
OUT="/tmp/psg_cricket.out"
npx playwright test tests/specs/planetsports/PSG.cricket.Animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🏏" "PSG Cricket – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🏏 PSG Cricket – Test Results" "$BODY"

# 3. PSG NFL
echo ""
echo "========================================"
echo "3/11: PSG NFL"
echo "========================================"
OUT="/tmp/psg_nfl.out"
npx playwright test tests/specs/planetsports/PSG.NFL.Animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🏈" "PSG NFL – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🏈 PSG NFL – Test Results" "$BODY"

# 4. PSG Tennis
echo ""
echo "========================================"
echo "4/11: PSG Tennis"
echo "========================================"
OUT="/tmp/psg_tennis.out"
npx playwright test tests/specs/planetsports/PSG.Tennis.Animations.Spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🎾" "PSG Tennis – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🎾 PSG Tennis – Test Results" "$BODY"

# 5. Vodacom
echo ""
echo "========================================"
echo "5/11: Vodacom"
echo "========================================"
bash scripts/run_vodacom_email.sh || true

# 6. PlanetF1
echo ""
echo "========================================"
echo "6/11: PlanetF1"
echo "========================================"
OUT="/tmp/planetf1.out"
npx playwright test tests/specs/planetf1/Planetf1.webpages.spec.ts --project=chromium 2>&1 | tee "$OUT" || true

# Extract tab details with load times for Automated Results format
tab_list=$(grep "✅ PASS:" "$OUT" | sed 's/^/✅ /' | nl -w1 -s'.  ')
tabs_ok=$(grep -c "✅ PASS:" "$OUT" || echo "0")
tabs_fail=$(grep -c "❌ FAIL:" "$OUT" || echo "0")
total_tabs=$((tabs_ok + tabs_fail))

uk_time=$(TZ='Europe/London' date '+%d %B %Y %H:%M:%S UK Time')
BODY="<div style=\"font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif\">"
BODY+="<h2>🏎️ PlanetF1 – Automated Results</h2>"
BODY+="<p><strong>Run Time:</strong> ${uk_time}</p>"
BODY+="<p><strong>Total:</strong> ${total_tabs} | <strong>Pass:</strong> ${tabs_ok} | <strong>Fail:</strong> ${tabs_fail} | <strong>Success:</strong> $(( total_tabs>0 ? (tabs_ok*100/total_tabs) : 0 ))%</p>"
if [ -n "$tab_list" ]; then
  BODY+="<h3>Page Results</h3>"
  BODY+="<pre style=\"white-space:pre-wrap;font-family:monospace\">${tab_list}</pre>"
fi
BODY+="</div>"
send_email "🏎️ PlanetF1 – Test Results" "$BODY"

# 7. TeamTalk
echo ""
echo "========================================"
echo "7/11: TeamTalk"
echo "========================================"
OUT="/tmp/teamtalk.out"
npx playwright test tests/specs/teamtalk/teamtlkweb.spec.ts --project=chromium 2>&1 | tee "$OUT" || true

# Extract team results for Automated Results format
team_list=$( ( grep "✅ Team .* loaded" "$OUT" 2>/dev/null | sed 's/^✅ Team /✅ /; s/ loaded with no broken images//'; grep "❌ Team .* failed" "$OUT" 2>/dev/null | sed 's/^❌ Team /❌ /; s/ failed to load.*//') | nl -w1 -s'.  ' )
teams_ok=$(grep -c "✅ Team .* loaded" "$OUT" || echo "0")
teams_fail=$(grep -c "❌ Team .* failed" "$OUT" || echo "0")
total_teams=$((teams_ok + teams_fail))

uk_time=$(TZ='Europe/London' date '+%d %B %Y %H:%M:%S UK Time')
BODY="<div style=\"font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif\">"
BODY+="<h2>⚽ TeamTalk – Automated Results</h2>"
BODY+="<p><strong>Run Time:</strong> ${uk_time}</p>"
BODY+="<p><strong>Total:</strong> ${total_teams} | <strong>Pass:</strong> ${teams_ok} | <strong>Fail:</strong> ${teams_fail} | <strong>Success:</strong> $(( total_teams>0 ? (teams_ok*100/total_teams) : 0 ))%</p>"
if [ -n "$team_list" ]; then
  BODY+="<h3>Team Results</h3>"
  BODY+="<pre style=\"white-space:pre-wrap;font-family:monospace\">${team_list}</pre>"
fi
BODY+="</div>"
send_email "⚽ TeamTalk – Test Results" "$BODY"

# 8. DragonSport Football
echo ""
echo "========================================"
echo "8/11: DragonSport Football"
echo "========================================"
OUT="/tmp/ds_football.out"
npx playwright test tests/specs/dragonbet/DragonSport.Football.animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "⚽" "DragonSport Football – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "⚽ DragonSport Football – Test Results" "$BODY"

# 9. DragonSport Cricket
echo ""
echo "========================================"
echo "9/11: DragonSport Cricket"
echo "========================================"
OUT="/tmp/ds_cricket.out"
npx playwright test tests/specs/dragonbet/DragonSport.Cricket.animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🏏" "DragonSport Cricket – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🏏 DragonSport Cricket – Test Results" "$BODY"

# 10. DragonSport Tennis
echo ""
echo "========================================"
echo "10/11: DragonSport Tennis"
echo "========================================"
OUT="/tmp/ds_tennis.out"
npx playwright test tests/specs/dragonbet/DragonSport.Tennis.animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🎾" "DragonSport Tennis – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🎾 DragonSport Tennis – Test Results" "$BODY"

# 11. DragonSport NFL
echo ""
echo "========================================"
echo "11/11: DragonSport NFL"
echo "========================================"
OUT="/tmp/ds_nfl.out"
npx playwright test tests/specs/dragonbet/DragonSport.NFL.animations.spec.ts --project=chromium 2>&1 | tee "$OUT" || true
RES=$(parse_results "$OUT")
PASS=$(echo "$RES" | cut -d',' -f1)
FAIL=$(echo "$RES" | cut -d',' -f2)
BODY=$(build_detailed_email "🏈" "DragonSport NFL – Animation Test Results" "$PASS" "$FAIL" "$OUT")
send_email "🏈 DragonSport NFL – Test Results" "$BODY"

echo ""
echo "✅ All 11 tests completed at $(TZ='Europe/London' date '+%Y-%m-%d %H:%M:%S UK Time')"
